dist: trusty
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz

git:
  depth: 1

env:
  global:
    - GH_REPO_REF: github.com/d-ronin/doxygen.git
    - IGNORE_MISSING_TOOLCHAIN: true

script:
  - cd $TRAVIS_BUILD_DIR && ./travis-docs.sh
