var dir_863ba33eb3f257a4a7e1d8f002fc2d06 =
[
    [ "projections", "dir_0600a6db23b9447c99f4fb242e9d0dfc.html", "dir_0600a6db23b9447c99f4fb242e9d0dfc" ],
    [ "copyrightstrings.h", "copyrightstrings_8h.html", null ],
    [ "core.cpp", "core_8cpp.html", null ],
    [ "core.h", "core_8h.html", null ],
    [ "debugheader.h", "internals_2debugheader_8h.html", null ],
    [ "loadtask.cpp", "loadtask_8cpp.html", "loadtask_8cpp" ],
    [ "loadtask.h", "loadtask_8h.html", null ],
    [ "mousewheelzoomtype.cpp", "mousewheelzoomtype_8cpp.html", null ],
    [ "mousewheelzoomtype.h", "mousewheelzoomtype_8h.html", null ],
    [ "pointlatlng.cpp", "pointlatlng_8cpp.html", "pointlatlng_8cpp" ],
    [ "pointlatlng.h", "pointlatlng_8h.html", null ],
    [ "pureprojection.cpp", "pureprojection_8cpp.html", null ],
    [ "pureprojection.h", "pureprojection_8h.html", null ],
    [ "rectangle.cpp", "rectangle_8cpp.html", "rectangle_8cpp" ],
    [ "rectangle.h", "rectangle_8h.html", null ],
    [ "rectlatlng.cpp", "rectlatlng_8cpp.html", "rectlatlng_8cpp" ],
    [ "rectlatlng.h", "rectlatlng_8h.html", null ],
    [ "sizelatlng.cpp", "sizelatlng_8cpp.html", "sizelatlng_8cpp" ],
    [ "sizelatlng.h", "sizelatlng_8h.html", null ],
    [ "tile.cpp", "tile_8cpp.html", null ],
    [ "tile.h", "tile_8h.html", null ],
    [ "tilematrix.cpp", "tilematrix_8cpp.html", null ],
    [ "tilematrix.h", "tilematrix_8h.html", null ]
];