var group___g_c_s_plugins =
[
    [ "Importexportplugin", "group__importexportplugin.html", "group__importexportplugin" ],
    [ "QML Viewer Plugin", "group___o_p_map_plugin.html", "group___o_p_map_plugin" ],
    [ "Viewer Plugin", "group___q_m_l.html", "group___q_m_l" ],
    [ "AeroQuad boards support Plugin", "group___boards___aero_quad_plugin.html", "group___boards___aero_quad_plugin" ],
    [ "BrainFPV boards support Plugin", "group___boards___brain_f_p_v.html", "group___boards___brain_f_p_v" ],
    [ "Brotronics boards support Plugin", "group___boards___brotronics.html", "group___boards___brotronics" ],
    [ "dRonin board support plugin", "group___boards__d_ronin.html", "group___boards__d_ronin" ],
    [ "DTF boards support Plugin", "group___boards___d_t_f.html", "group___boards___d_t_f" ],
    [ "Matek boards support Plugin", "group___boards___matek_plugin.html", "group___boards___matek_plugin" ],
    [ "OpenPilot boards support Plugin", "group___boards___open_pilot_plugin.html", "group___boards___open_pilot_plugin" ],
    [ "Quantec boards support Plugin", "group___boards___quantec.html", "group___boards___quantec" ],
    [ "Tau Labs boards support Plugin", "group___boards___tau_labs_plugin.html", "group___boards___tau_labs_plugin" ],
    [ "Config Plugin", "group___config_plugin.html", "group___config_plugin" ],
    [ "Plugin", "group___config.html", "group___config" ],
    [ "Core Plugin", "group___core_plugin.html", "group___core_plugin" ],
    [ "Debug Gadget Plugin", "group___debug_gadget_plugin.html", "group___debug_gadget_plugin" ],
    [ "Dial Plugin", "group___dial_plugin.html", "group___dial_plugin" ],
    [ "Empty Gadget Plugin", "group___empty_gadget_plugin.html", "group___empty_gadget_plugin" ],
    [ "GCSControl", "group___g_c_s_control.html", "group___g_c_s_control" ],
    [ "GCSControl Gadget Plugin", "group___g_c_s_control_gadget_plugin.html", "group___g_c_s_control_gadget_plugin" ],
    [ "GPS Gadget Plugin", "group___g_p_s_gadget_plugin.html", "group___g_p_s_gadget_plugin" ],
    [ "IP Telemetry Plugin", "group___i_p_conn_plugin.html", "group___i_p_conn_plugin" ],
    [ "KmlExportPlugin", "group___kml_export_plugin.html", "group___kml_export_plugin" ],
    [ "Linear Dial Plugin", "group___linear_dial_plugin.html", "group___linear_dial_plugin" ],
    [ "Logging", "group___logging.html", "group___logging" ],
    [ "Loggingplugin", "group__loggingplugin.html", "group__loggingplugin" ],
    [ "ModelView Plugin", "group___model_view_plugin.html", "group___model_view_plugin" ],
    [ "Notification plugin", "group___notify_plugin.html", "group___notify_plugin" ],
    [ "Planner Pluggin", "group___path.html", "group___path" ],
    [ "Path Planner Gadget Plugin", "group___path_planner_gadget_plugin.html", "group___path_planner_gadget_plugin" ],
    [ "Map Plugin", "group___path_planner.html", "group___path_planner" ],
    [ "Raw HID Plugin", "group___raw_h_i_d_plugin.html", "group___raw_h_i_d_plugin" ],
    [ "Scope Gadget Plugin", "group___scope_plugin.html", "group___scope_plugin" ],
    [ "UAVObjects Plugin", "group___u_a_v_objects_plugin.html", "group___u_a_v_objects_plugin" ],
    [ "Serial Connection Plugin", "group___serial_plugin.html", "group___serial_plugin" ],
    [ "Setup Wizard", "group___setup_wizard.html", "group___setup_wizard" ],
    [ "Alarms Messaging Plugin", "group___system.html", "group___system" ],
    [ "System Health Plugin", "group___system_health_plugin.html", "group___system_health_plugin" ],
    [ "TelemetryScheduler Plugin", "group___telemetry_scheduler_plugin.html", null ],
    [ "UAVObject Browser Plugin", "group___u_a_v_object_browser_plugin.html", "group___u_a_v_object_browser_plugin" ],
    [ "UAVObjectUtil Plugin", "group___u_a_v_object_util_plugin.html", "group___u_a_v_object_util_plugin" ],
    [ "UAVSettings Import/Export Plugin", "group___u_a_v_settings_import_export.html", "group___u_a_v_settings_import_export" ],
    [ "UAVTalk Plugin", "group___u_a_v_talk_plugin.html", "group___u_a_v_talk_plugin" ],
    [ "Uploader Plugin", "group___uploader.html", "group___uploader" ],
    [ "UsageStats Gadget Plugin", "group___usage_stats_plugin.html", "group___usage_stats_plugin" ],
    [ "Welcome Plugin", "group___welcome_plugin.html", "group___welcome_plugin" ]
];