var modules =
[
    [ "PIOS Core hardware abstraction layer", "group___p_i_o_s.html", "group___p_i_o_s" ],
    [ "UDP Functions", "group___p_i_o_s___u_d_p.html", "group___p_i_o_s___u_d_p" ],
    [ "SERIAL Functions", "group___p_i_o_s___s_e_r_i_a_l.html", null ],
    [ "Tau Labs Libraries", "group___tau_labs_libraries.html", "group___tau_labs_libraries" ],
    [ "Utilities", "group___math.html", "group___math" ],
    [ "Libraries", "group___libraries.html", "group___libraries" ],
    [ "Tau Labs Modules", "group___tau_labs_modules.html", "group___tau_labs_modules" ],
    [ "Labs Modules", "group___tau.html", "group___tau" ],
    [ "GPS Module", "group___g_s_p_module.html", "group___g_s_p_module" ],
    [ "dRonin Modules", "group___modules.html", "group___modules" ],
    [ "Modules", "group__d_ronin.html", "group__d_ronin" ],
    [ "RGB Led functions", "group___r_g_b_l_e_d.html", null ],
    [ "Inline delay subsystem", "group___p_i_o_s___i_n_l_i_n_e_d_e_l_a_y.html", "group___p_i_o_s___i_n_l_i_n_e_d_e_l_a_y" ],
    [ "Tau Labs Bootloaders", "group___tau_labs_bootloader.html", "group___tau_labs_bootloader" ],
    [ "AeroQuad Targets", "group___aero_quad_targets.html", "group___aero_quad_targets" ],
    [ "CMSIS", "group___c_m_s_i_s.html", "group___c_m_s_i_s" ],
    [ "USB_OTG_DRIVER", "group___u_s_b___o_t_g___d_r_i_v_e_r.html", "group___u_s_b___o_t_g___d_r_i_v_e_r" ],
    [ "Config", "group__config.html", "group__config" ],
    [ "HAL_CONF", "group___h_a_l___c_o_n_f.html", "group___h_a_l___c_o_n_f" ],
    [ "Bootloaders", "group___bootloader.html", "group___bootloader" ],
    [ "Tau Labs Targets", "group___tau_labs_targets.html", "group___tau_labs_targets" ],
    [ "BrainFPV Targets", "group___brain_f_p_v_targets.html", "group___brain_f_p_v_targets" ],
    [ "DTFc DTF bootloader", "group__dtfc_b_l.html", "group__dtfc_b_l" ],
    [ "Target Boards", "group___targets.html", "group___targets" ],
    [ "Lumenier Lux bootloader", "group__lux_b_l.html", "group__lux_b_l" ],
    [ "Lux support files", "group___lumenier.html", "group___lumenier" ],
    [ "family support files", "group___naze.html", "group___naze" ],
    [ "Boards", "group___boards.html", "group___boards" ],
    [ "UnitTests", "group___unit_tests.html", "group___unit_tests" ],
    [ "Tau Labs Core components", "group___tau_labs_core.html", "group___tau_labs_core" ]
];